version: '3'

services:
  uphint:
    image: node:16-alpine
    container_name: 'uphint'
    working_dir: '/app'
    volumes:
      - ./:/app

  uphint_e2e_test:
    image: ghcr.io/puppeteer/puppeteer:18.1.0
    container_name: 'uphint_e2e_test'
    working_dir: '/app'
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./:/app
